name: Beta Release PR

on:
  push:
    branches:
      - develop

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Beta Release PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: yarn

      - name: Create Beta Release Pull Request
        uses: changesets/action@v1
        with:
          version: yarn beta-ver
          commit: 'ci: version packages [ci skip]'
          title: 'ci: new beta release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
