name: Create version PR from release branch

on:
  push:
    branches:
      - 'release**'
      - 'hotfix**'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Create version PR from release branch
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Cache turbo build setup
        uses: actions/cache@v3
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: yarn

      - name: Bump Changeset Version
        run: yarn ver

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'ci: bump package version'
          commit_options: '--no-verify'

      - name: Create Release Pull Requests
        env:
          GITHUB_TOKEN: ${{ secrets.DEV_GITHUB_TOKEN }}
          MAIN_TITLE: 'Release: Merge to publish new version to npm'
          MAIN_BODY: 'Please review and merge this Pull Request. **Caution: Merge to main branch will trigger publish to npm.**'
          DEV_TITLE: 'Release: Merge back new version to develop'
          DEV_BODY: 'Merge new prod release back to develop'
        run: |
          gh pr create --title "$MAIN_TITLE" --body "$MAIN_BODY" --base main && gh pr create --title "$DEV_TITLE" --body "$DEV_BODY" --base develop
